### ISSUE TITLE
Separate checker from Grunt task wrapper

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/grunt-banana-checker#13]
This will let us more easily switch to / also support e.g. Gulp

**Comment by Krinkle** [comment]
In Navigation Timing extension, after <https://gerrit.wikimedia.org/r/#/c/mediawiki/extensions/NavigationTiming/+/483020/>, banana-checker would be the only reason for a Gruntfile to remain.

I propose that we pick this task by up separating the code, but keep in the same repository for now, as follows:

1. Programmatic interface under `src/` (one or more files), and set `package.json#main` to `src/index.js` or whatever filename we'll use that exports the public API. The public API would be a function that takes 2 parameter. A directory path to operate on, and an options object like the one we currently accept as a Grunt task.

2. CLI interface under `bin/banana-checker`, very simple Node.js program that invokes the public API, takes one parameter (directory), defaulting to `path.join( process.cwd(), 'i18n' );`. It optionally reads `package.json#banana-checker` for any setting overrides (merge with default options).

3. The existing Grunt task, under `tasks/` like today. I realised today that `grunt.loadNpmTasks()` doesn't require the package to be named `grunt-` or to exclusively export grunt tasks. Rather, it just reads it from any `tasks/` sub directory in the published package. So we can continue to do that. We may want to consider renaming the package `banana-checker` at the next major semver, but either way, it can remain together under one roof, with `tasks/banana` simply a 5-line entry point we provide.
