### ISSUE TITLE
0.3.0 causing problems for me

### ISSUE THREAD

**Issue by paladox** [wikimedia/grunt-banana-checker#31]
Hi since trying to upgrade to 0.3.0 I am getting this error in the metrolook skin

14:27:29 >> The "en-gb" translation has 1 duplicate translation:
14:27:29 >> The translation of "metrolook-guest" is a duplicate of the primary message.
14:27:29 Warning: Task "banana:Metrolook" failed. Use --force to continue.
14:27:29 
14:27:29 Aborted due to warnings.

I look at the translations and there is no duplicate.

**Comment by Krinkle** [comment]
There is a duplicate:

https://github.com/wikimedia/mediawiki-skins-Metrolook/blob/9b7b62277a9afa1640d01314dbb39807f442b0c6/i18n/en.json
```
	"metrolook-guest": "Guest",
```
https://github.com/wikimedia/mediawiki-skins-Metrolook/blob/9b7b62277a9afa1640d01314dbb39807f442b0c6/i18n/en-gb.json
```
	"metrolook-guest": "Guest",
```

Translations should only submit overrides, not copies of the same. If you want to allow this, set `disallowDuplicateTranslations: false` for banana options in your Gruntfile.
