### ISSUE TITLE
Add option to not require @metadata blocks

### ISSUE THREAD

**Issue by legoktm** [wikimedia/grunt-banana-checker#44]
See https://gerrit.wikimedia.org/r/#/c/248670/ for example, adding an empty `@metadata` block isn't useful at all.

CC @siebrand

**Comment by siebrand** [comment]
Thank you, Kunal.

**Comment by ricordisamoa** [comment]
`requireMetadata: false`?

**Comment by jayvdb** [comment]
Isnt `metadata` necessary, or at least highly desirable, for cc-by 3.0 license attribution purposes?

**Comment by ricordisamoa** [comment]
> Isnt `metadata` necessary, or at least highly desirable, for cc-by 3.0 license attribution purposes?

Is there any requirement that every 'banana' file has to come from TranslateWiki or be released under CC-BY?

**Comment by jayvdb** [comment]
> Is there any requirement that every 'banana' file has to come from TranslateWiki or be released under CC-BY?

Technically probably not.

e.g. We have the situation in pywikibot were some translations come from out of MIT source code, and others from CC-BY TranslateWiki.  This creates problems regarding how to explain the license to our re-users.  https://phabricator.wikimedia.org/T100670

It is easier to assume that all files in a i18n repo/directory are CC-BY whenever TranslateWiki is connected.

So, I guess that question could be rephrased as

Does Wikimedia run `grunt-banana-checker` on any repo which isnt including translations from TranslateWiki ?

There may be specific i18n files which are not every going to ever see updates from TranslateWiki.  It would be good to discuss them specifically.

The case which was the reason for this issue being created does not appear to be one of them; see my comment on https://gerrit.wikimedia.org/r/#/c/248670/1/i18n/aeb-arab.json,cm

**Comment by siebrand** [comment]
> We have the situation in pywikibot were some translations come from out of MIT source code, and others from CC-BY TranslateWiki. This creates problems regarding how to explain the license to our re-users.

This is an incorrect interpretation of the translatewiki.net (not TranslateWiki) license. It reads clearly on https://translatewiki.net/wiki/Project:About: "Translations by translators are licensed CC BY 3.0, and derivative works may also be licensed under the licenses of the respective Free and Open Source projects the translations have been or will be added to."

**Comment by jayvdb** [comment]
Hmm, interesting.  So then the `@metadata` is not needed for any project which does not need metadata to comply with its license?
i.e. in the case of pywikibot-i18n, we could state the repo is MIT as that was its historical license, and not collect any metadata from Translatewiki (i.e. turn them off, like this issue proposes), but any significant translation contributor could submit a patch to add their name to the pywikibot-core CREDITS file...?

**Comment by ricordisamoa** [comment]
The default value of `true` for `requireMetadata` should be left as is in Wikimedia repositories, whereas anyone not needing license compliance can just make it `false`. I think we're all set?

**Comment by jayvdb** [comment]
We're not set until we know there is someone who benefits from this feature, otherwise it is technical debt, and a feature not likely to be maintained by the predominately wikimedia dev team.
If it is not going to be used by Wikimedia repositories, has anyone else requested this feature?

**Comment by ricordisamoa** [comment]
> If it is not going to be used by Wikimedia repositories, has anyone else requested this feature?

I have used the feature in the past (https://github.com/ricordisamoa/dewkin/commit/946d231c28611225c5a09b3f4e0cc0fba0eab8ec) and in my opinion it'd be a pity if potential users of grunt-banana-checker were deterred just because they manage attribution differently.

**Comment by Krinkle** [comment]
> We're not set until we know there is someone who benefits from this feature, otherwise it is technical debt, and a feature not likely to be maintained by the predominately Wikimedia dev team.

This is not a complex or major feature, and has unit tests. It has a valid use and we'll make sure it keeps working. It's been in banana checker since v0.3.0 (f487f683c7ef02bc3a).

Closing this issue as resolved since the original request seems to be satisfied by the `requireMetadata` option.
